### ISSUE TITLE
XenForo_Upload

### ISSUE THREAD

**Issue by JeremyHutchings** [UnderRatedBrilliance/XenforoBridge#12]
When using XenForo_Upload via the bridge you'd have to pass in the fileName and tempFile, as per : 

```
        XenForo_Upload
        ....
        ....
    /**
     * Constructor.
     *
     * @param string $fileName User-supplied file name
     * @param string $tempFile Upload temporary file name; this can be an empty string to account for uploads that are too large
     */
    public function __construct($fileName, $tempFile)
    {
```

How does `XF::getXenforoModel('XenForo_Upload')` deal with that ?

Or as it's not technically a model, how would it be access via the bridge ?

**Comment by JeremyHutchings** [comment]
Currently doing this, though doesn't feel correct : 

```
            $xfAuto = \XenForo_Autoloader::getInstance();
            require_once($xfAuto->autoloaderClassToFile('XenForo_Upload'));
```

**Comment by gabarba** [comment]
As long as the Xenforo Autoloader has already been initialized you should be able to just call the class like so 

``` php
$xenUpload = new XenForo_Upload($filename,$tempFile)

```

Let me know if that doesn't work.

**Comment by JeremyHutchings** [comment]
I really need to be awake before I code ;) 

Thanks, can close.
