### ISSUE TITLE
The user is not known to laravel after logging in

### ISSUE THREAD

**Issue by ILLuMiNaTe7** [UnderRatedBrilliance/XenforoBridge#13]
After i login laravel doesnt seem to know that im logged in.

Did i do something wrong? if so what

  #xenforoOptions: null
  #visitor: Visitor {#124}
  #template: null
  #user: null

**Comment by JeremyHutchings** [comment]
What is the code ? How have you implemented the bridge ?

**Comment by gabarba** [comment]
I'm not sure I follow you, did you log in using Laravel's authentication or Xenforo's?

As Jeremy mentioned I won't be able to help you unless you describe how you implemented the bridge and or plan on using it. In his particular case he is authenticating using Laravel then creating the user and starting a session in Xenforo with said user. 

I personally use Xenforo for the authentication and user management so I just need to see if the user has already been authenticated by Xenforo.

From my understanding you just have a dump of the XenforoBridge class above, did you run the isLoggedIn() method to see what value is returned?

**Comment by gabarba** [comment]
Closing due to no response from @ILLuMiNaTe7
