### ISSUE TITLE
Laravel 5 Support ?

### ISSUE THREAD

**Issue by mehrdd** [UnderRatedBrilliance/XenforoBridge#5]
Hi,
Will this package work with laravel 5 ?

thanks.

**Comment by huyhvq** [comment]
Simple but Extendable Bridge for Xenforo to use with Laravel 5 :)

**Comment by gabarba** [comment]
Yea but I haven't updated the readme in a while. I honestly didn't know anybody was viewing this repo as it is far from being a complete package yet I haven't really made a push to advertise it. I'm currently using it on Laravel 5 with no issues. I haven't tested it with 4 recently as my current project that I am using it for is on Laravel 5. If you guys have any other issues or are looking for some specific features let me know I would love to hear your feedback.

**Comment by mehrdd** [comment]
@gabarba, There's no need to advertise for packages like this ! when we need it, we'll find it !
Thanks,
i will try that .. ;)

Regards.
